# Generated by Django 5.0.1 on 2024-01-05 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emp', models.CharField(help_text='Nombre completo de la empresa.', max_length=255, unique=True, verbose_name='Nombre Empresa')),
                ('documento', models.CharField(help_text='Ej: 1234567890123.', max_length=20, unique=True, verbose_name='Numero de Identificación')),
                ('direccion', models.CharField(help_text='Ej: Calle 100 # 40 - 60', max_length=100, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=50, verbose_name='Nombre de Sede')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_serv', models.CharField(help_text='Nombre del servicio', max_length=100, verbose_name='Nombre de los servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_brig', models.CharField(help_text='Nombre completo de la brigada.', max_length=255, verbose_name='Nombre Brigada')),
                ('f_inicio', models.DateField(help_text='Programación de asistencia de la brigada.', verbose_name='fecha de Programación')),
                ('f_final', models.DateField(help_text='Programación de asistencia del paciente.', verbose_name='fecha de Programación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuar')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.empresa', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Datos adicionales para tener en cuenta', null=True, verbose_name='Observaciones adicionales')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.brigada', verbose_name='Nombre de la briga')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.brigada', verbose_name='Nombre de la briga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personal que va a la brigada')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.brigada', verbose_name='Nombre de la briga')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.servicio', verbose_name='Los servicios que se realizan')),
            ],
        ),
    ]
